ERROR:    Traceback (most recent call last):
  File "C:\Users\342534\Desktop\Telecom Standards Management\telecom_venv\Lib\site-packages\starlette\routing.py", line 694, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\342534\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\342534\Desktop\Telecom Standards Management\telecom_venv\Lib\site-packages\fastapi\routing.py", line 134, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\342534\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\342534\Desktop\Telecom Standards Management\telecom_venv\Lib\site-packages\fastapi\routing.py", line 134, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\342534\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\342534\Desktop\Telecom Standards Management\telecom_venv\Lib\site-packages\fastapi\routing.py", line 134, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\342534\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\342534\Desktop\Telecom Standards Management\telecom_venv\Lib\site-packages\fastapi\routing.py", line 134, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\342534\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\342534\Desktop\Telecom Standards Management\telecom_venv\Lib\site-packages\fastapi\routing.py", line 134, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\342534\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
                 ~~~~~^^^^^^^^^^
TypeError: 'coroutine' object is not an async iterator

C:\Users\342534\Desktop\Telecom Standards Management\telecom_venv\Lib\site-packages\uvicorn\lifespan\on.py:91: RuntimeWarning: coroutine 'lifespan' was never awaited
  return
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
ERROR:    Application startup failed. Exiting.
